# Generated by Django 3.1.5 on 2021-05-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='arch',
            new_name='file',
        ),
    ]
